site_name: Single Source Demo
repo_url: https://github.com/Recours/recours.github.io
repo_name: way-to-single-source
theme:
    name: material
    logo: TWD_favicon.png
    favicon: TWD_logo.png
    features:
        - navigation.tabs
    font: false # отключает скачивание шрифтов для отрисовки темы материал из Гугла
    icon:
        repo: fontawesome/brands/git-alt
extra_css:
    - material-styles.css
nav:
    - Делаем условия в контенте:
        - Документ для Ежика: first-aid-guide.md
        - Документ для Копатыча: for-eshik-guide.md
    - Управляем уровнем заголовков: 
        - С помощью условия: if-condition-headers.md
        - В 5 раз меньше кода: smart-headers.md
    - Управляем путями для картинок:
        - Улей для Копатыча: ulei-kopatycha.md
        - Улей для Ежика: ulei-eshika.md
markdown_extensions:
    - pymdownx.superfences # более гибкое оформление блоков https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
    - admonition
plugins:
    - search:
        lang:
          - ru
    - macros